version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    hostname: clickhouse
    ports:
      - "8124:8123" # HTTP interface
      - "9001:9000" # Native TCP interface
    volumes:
      - ./user_directories/config.xml:/etc/clickhouse-server/user_directories/config.xml
      - ./user_directories/users.xml:/etc/clickhouse-server/user_directories/users.xml
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=guardian
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    networks:
      - clickhouse-network
  fastapi:
    build:
      context: ../..
      dockerfile: services/clickhouse/Dockerfile
    container_name: fastapi-app
    depends_on:
      - clickhouse
    environment:
      - DATABASE_TYPE=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DATABASE=guardian
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ../requirements.txt:/app/requirements.txt
      - ../.env:/app/.env
    networks:
      - clickhouse-network
    restart: unless-stopped

networks:
  clickhouse-network:
    driver: bridge

volumes:
  clickhouse-data:
  clickhouse-logs:
