services:
  db:
    image: ankane/pgvector:latest
    container_name: rag
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent volume for DB storage
      - ./init:/docker-entrypoint-initdb.d # SQL/init scripts on startup
    ports:
      - 5430:5432 # docker:postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-VectorEmbeds}
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}
    ulimits:                                          
      nofile:
        soft: 262144
        hard: 262144

  app:
    build:
      context: ..
      dockerfile: postgres/Dockerfile
    container_name: rag-app
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-VectorEmbeds}
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}
      - GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
    volumes:
      - ../scripts:/app/scripts
      - ../requirements.txt:/app/requirements.txt
      - ../services/postgres:/app/services/postgres
    working_dir: /app
    command: ["uvicorn", "services.postgres.postgres_controller:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

volumes:
  db_data: