services:
  db:
    image: ankane/pgvector:latest
    container_name: rag-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent volume for DB storage
      - ./init:/docker-entrypoint-initdb.d # SQL/init scripts on startup
    ports:
      - 5430:5432 # docker:postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-VectorEmbeds}
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  app:
    env_file: "../../.env"
    build:
      context: ../..
      dockerfile: services/postgres/Dockerfile
    container_name: rag-app
    depends_on:
      - db
    ports:
      - 8001:8001
    environment:
      - DATABASE_TYPE=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-VectorEmbeds}
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}
    volumes:
      - .:/app

    working_dir: /app
    restart: unless-stopped

volumes:
  db_data:
